#!/usr/bin/with-contenv bash
# # This script sets up the laravel files

# Copy site files to /config
echo "Copying latest site files to config"
cp -rfT /site/ /config/www/

# Check for DB
# if [ ! -f /config/laravel.db ]; then
#     echo "Database file not found! Creating empty database"
#     touch /config/speed.db
# else
#     echo "Database file exists"
#     chown abc:abc /config/laravel.db
# fi

# Check for .env
# if [ ! -f /config/www/.env ]; then
#     echo "Env file not found! Creating .env file"
#     cp /site/.env.example /config/www/.env
# else
#     echo "Env file exists"
# fi

# Update env file with SQLite location
# sed "s,DB_DATABASE=.*,DB_DATABASE=/config/laravel.db," -i.bak /config/www/.env

# echo "Running database migrations"
# php /config/www/artisan migrate

# Check app key exists
# if grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /config/www/.env > /dev/null; then
#     echo "App key exists"
# else
#     echo "Generating app key"
#     php /config/www/artisan key:generate
# fi

# Check JWT secret exists
# if grep -E "JWT_SECRET=[0-9A-Za-z:+\/=]{1,}" /config/www/.env > /dev/null ; then
#     echo "JWT secret exists"
# else
#     echo "Generating JWT secret"
#     php /config/www/artisan jwt:secret
# fi

mkdir -p /config/log/laravel

cp /defaults/crontab /etc/crontabs/root

chown -R abc:abc /config
